# Generated by Django 2.0.1 on 2018-02-02 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=64, verbose_name='Название ветки форума')),
                ('url', models.CharField(default=None, max_length=128, verbose_name='URL сайта')),
                ('pages', models.IntegerField(default=0, verbose_name='Скопировано страниц')),
                ('pagesTotal', models.IntegerField(default=0, verbose_name='Количество страниц')),
                ('isActive', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name_plural': 'Ветки форумов',
                'verbose_name': 'Ветка форума',
            },
        ),
        migrations.CreateModel(
            name='ForumUsers',
            fields=[
                ('id', models.CharField(default=None, max_length=12, primary_key=True, serialize=False, verbose_name='ID пользователя форума')),
                ('name', models.CharField(default=None, max_length=32, verbose_name='Имя пользователя')),
            ],
            options={
                'verbose_name_plural': 'Пользователи форума',
                'verbose_name': 'Пользователь форума',
            },
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=24, verbose_name='Название сайта')),
                ('short', models.CharField(blank=True, default='', max_length=2, verbose_name='Краткое название сайта')),
            ],
            options={
                'verbose_name_plural': 'Сайты',
                'verbose_name': 'Сайт',
            },
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.CharField(default=None, max_length=12, primary_key=True, serialize=False, verbose_name='ID поста форума')),
                ('topicText', models.TextField(default=None, verbose_name='Содержание поста')),
                ('datePost', models.DateTimeField(verbose_name='Дата опубликования')),
                ('dateModified', models.DateTimeField(verbose_name='Дата сохранения')),
                ('site', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forumTopics.Forums', verbose_name='Название ветки форума')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forumTopics.ForumUsers', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Топики',
                'verbose_name': 'Топик',
            },
        ),
        migrations.AddField(
            model_name='forumusers',
            name='site',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forumTopics.Sites', verbose_name='Cайт'),
        ),
        migrations.AddField(
            model_name='forums',
            name='site',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forumTopics.Sites', verbose_name='Название сайта'),
        ),
    ]
