# Generated by Django 2.0.1 on 2018-02-02 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumTopics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forums',
            name='pagesTotal',
            field=models.IntegerField(default=0, verbose_name='Всего страниц'),
        ),
    ]
