# Generated by Django 2.0.2 on 2018-03-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumTopics', '0003_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='еmployees',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
    ]
