# Generated by Django 2.0.2 on 2018-03-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumTopics', '0004_auto_20180310_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='еmployees',
            name='patronymic',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Отчество'),
        ),
    ]
