# Generated by Django 2.0.2 on 2018-03-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumTopics', '0005_auto_20180312_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
    ]
