# Generated by Django 2.0.3 on 2018-04-01 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumTopics', '0006_sites_isactive'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Еmployees',
            new_name='Employees',
        ),
    ]
