# Generated by Django 2.0.3 on 2018-04-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumTopics', '0007_auto_20180401_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='url',
            field=models.URLField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
