# Generated by Django 2.0.3 on 2018-04-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumTopics', '0008_topics_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='url',
            field=models.URLField(blank=True, default='#', max_length=256, null=True),
        ),
    ]
