# Generated by Django 2.0.3 on 2018-04-15 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forumTopics', '0010_auto_20180413_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='forumTopics.ForumUsers', verbose_name='Пользователь'),
        ),
    ]
